# Generated by Django 4.1 on 2022-08-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounting_year',
            name='date',
        ),
        migrations.AlterField(
            model_name='accounting_year',
            name='fromdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='accounting_year',
            name='todate',
            field=models.DateField(),
        ),
    ]
