# Generated by Django 3.2.14 on 2022-07-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_arpproduct_arpservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arpproduct',
            name='purchase_price_with_tax',
        ),
        migrations.RemoveField(
            model_name='arpproduct',
            name='sale_price_with_tax',
        ),
        migrations.AddField(
            model_name='arpproduct',
            name='purchase_price_type',
            field=models.CharField(choices=[('withTax', 'with Tax'), ('withoutTax', 'without Tax')], default=133, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arpproduct',
            name='sale_price_type',
            field=models.CharField(choices=[('withTax', 'with Tax'), ('withoutTax', 'without Tax')], default=965, max_length=50),
            preserve_default=False,
        ),
    ]
