# Generated by Django 3.2.14 on 2022-07-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_rename_tax_gst_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gst',
            name='tax_value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
