# Generated by Django 3.2.14 on 2022-07-22 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_gst_tax_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arpproduct',
            name='tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.gst'),
        ),
    ]
