# Generated by Django 3.2.14 on 2022-07-22 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_arpproduct_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arpservice',
            name='sale_price_with_tax',
        ),
        migrations.AddField(
            model_name='arpservice',
            name='sale_price_type',
            field=models.CharField(choices=[('withTax', 'with Tax'), ('withoutTax', 'without Tax')], default=98, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arpservice',
            name='tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.gst'),
        ),
    ]
