# Generated by Django 3.2.14 on 2022-07-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_prpservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArpParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('opening_balance', models.CharField(max_length=100)),
                ('gst_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PrpParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('opening_balance', models.CharField(max_length=100)),
                ('gst_number', models.CharField(max_length=100)),
            ],
        ),
    ]
