# Generated by Django 3.2.14 on 2022-07-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_arpparty_prpparty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prpservice',
            name='service_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
